apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters-root
  namespace: argocd
spec:
  generators:
    - git:
        # Repositorio GitOps de plataforma en GitHub.
        repoURL: https://github.com/scanntech-dev/argocd-demo-repo.git
        revision: HEAD
        directories:
          - path: clusters/*
  template:
    metadata:
      name: "{{path.basename}}-root"
      namespace: argocd
      labels:
        platform.argocd.io/cluster: "{{path.basename}}"
    spec:
      project: clusters
      source:
        repoURL: https://github.com/scanntech-dev/argocd-demo-repo.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true


