apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/clusters-root
spec:
  project: platform-gitops
  source:
    repoURL: git@github.com:mtsdlf/argo-test.git
    targetRevision: HEAD
    path: clusters
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true


