apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: maven-dummy-app-team-example
  namespace: argocd
  labels:
    platform.argocd.io/domain: team-example
    platform.argocd.io/service: maven-dummy-app
    app.kubernetes.io/name: maven-dummy-app-gitops
    app.kubernetes.io/part-of: team-example
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: team-example-dev
          - env: qa
            namespace: team-example-qa
          - env: stg
            namespace: team-example-stg
  template:
    metadata:
      name: maven-dummy-app-{{env}}
      namespace: argocd
      labels:
        platform.argocd.io/domain: team-example
        platform.argocd.io/env: "{{env}}"
        platform.argocd.io/service: maven-dummy-app
      annotations:
        argocd.argoproj.io/sync-wave: "10"
    spec:
      project: team-example
      destination:
        namespace: "{{namespace}}"
        server: https://kubernetes.default.svc
      source:
        repoURL: git@github.com:mtsdlf/moneytree-gitops.git
        targetRevision: main
        path: "{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true


