apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      name: team-example
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io/team-example
      labels:
        platform.argocd.io/domain: team-example
    spec:
      description: Dominio team-example
      clusterResourceWhitelist:
        - group: ""
          kind: Namespace
      # Namespaces a los que puede desplegar este dominio.
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
        - namespace: team-example-dev
          server: https://kubernetes.default.svc
        - namespace: team-example-qa
          server: https://kubernetes.default.svc
        - namespace: team-example-stg
          server: https://kubernetes.default.svc
      # Recursos namespaced mínimos que puede gestionar el dominio.
      namespaceResourceWhitelist:
        - group: "*"
          kind: "*"
      namespaceResourceBlacklist:
        - group: ""
          kind: NetworkPolicy
      sourceRepos:
        - "git@github.com:mtsdlf/*"

  - apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: team-example-envs
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: team-example
    spec:
      generators:
        - list:
            elements:
              - project: team-example
                env: dev
                namespace: team-example-dev
              - project: team-example
                env: qa
                namespace: team-example-qa
              - project: team-example
                env: stg
                namespace: team-example-stg
      template:
        metadata:
          name: "{{project}}-{{env}}"
          namespace: argocd
          labels:
            platform.argocd.io/domain: "{{project}}"
            platform.argocd.io/env: "{{env}}"
        spec:
          project: "{{project}}"
          destination:
            namespace: "{{namespace}}"
            server: https://kubernetes.default.svc
          source:
            repoURL: git@github.com:mtsdlf/argo-test.git
            targetRevision: HEAD
            path: clusters/rke-dev-cluster1/resources/apps/{{project}}
            directory:
              recurse: true
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
              - ApplyOutOfSyncOnly=true